"""add phone number

Revision ID: 0cb9e9c52d4f
Revises: c718e875e870
Create Date: 2022-03-31 19:49:08.297161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb9e9c52d4f'
down_revision = 'c718e875e870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
